# to start: docker compose up -d
# this command as an alternative to docker run
# this can also be scheduled in cron
services:
  scuderia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scuderia
    environment:
      - POLYMARKET_PRIVATE_KEY=${POLYMARKET_PRIVATE_KEY}
      - SLACK_CLI_TOKEN=${SLACK_CLI_TOKEN}
      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - BUDGETCAPPERCENT=20