# to start: docker compose pull && docker compose up -d
# this command as an alternative to docker run
# this can also be scheduled in cron
services:
  scuderia:
    image: ghcr.io/alinflorin/scuderia:latest # or experimental or sha tag or version tag
    container_name: scuderia
    environment:
      - POLYMARKET_PRIVATE_KEY=${POLYMARKET_PRIVATE_KEY}
      - SLACK_CLI_TOKEN=${SLACK_CLI_TOKEN}
      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}
      - BUDGETCAPPERCENT=20